gmapdemo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='home'),
    url(r'^create_place/$', views.create_place, name='create_place'),
    url(r'^clear_database/$', views.clear_database, name='clear_database'),
]

job_evaluation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gmapdemo.urls', namespace='gmapdemo')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gmapdemo/models.py
from __future__ import unicode_literals

from django.db import models


class Place(models.Model):
	lat = models.CharField(max_length=100)
	lon = models.CharField(max_length=100)
	address = models.CharField(max_length=200)

	def __str__(self):
		return "{0} :: {1} :: {2}".format(self.lat, self.lon, self.address)

gmapdemo/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Place


def dashboard(request):
    places = Place.objects.all()
    return render(request, 'dashboard.html', {'places':places})

@csrf_exempt
def create_place(request):
    try:
        place = Place.objects.create( address = request.POST['address'],
                                       lat = request.POST['lat'],
                                       lon = request.POST['lng']
                                    )
        data = { 'status': 201, 'address': place.address, 'lat': place.lat, 'lon': place.lon }
    except Exception as e:
        data = { 'status': 500, 'errors': 'Something went wrong!' }

    return JsonResponse(data)


def clear_database(request):
    Place.objects.all().delete()
    return redirect('/dashboard')

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Job Evaluation: Senior Python/ Django Developer {% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      .page-header {
        margin-top: 0;
      }

      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div id="map" style="height: 400px;width: 100%;"></div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" id="places">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Address</th>
                        <th>Latitide</th>
                        <th>Longitude</th>
                    </tr>
                </thead>
                <tbody class="place_rows">
                    {% if places %}
                    
                        {% for place in places %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ place.address }}</td>
                                <td>{{ place.lat }}</td>
                                <td>{{ place.lon }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <p> No records! </p>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: -34.397, lng: 150.644},
                zoom: 8
            });

            map.addListener('click', function( event ){
                var geocoder = new google.maps.Geocoder;
                var infowindow = new google.maps.InfoWindow;

                geocoder.geocode({'location': event.latLng}, function(results, status) {
                    if (status === 'OK') {
                        if (results[0]) {
                            map.setZoom(11);
                            var marker = new google.maps.Marker({
                                position: event.latLng,
                                map: map
                            });
                            infowindow.setContent(results[0].formatted_address);
                            add_place(results[0].formatted_address, event.latLng.lat(), event.latLng.lng());
                            infowindow.open(map, marker);
                        } else {
                            console.log('No results found');
                        }
                    } else {
                        console.log('Geocoder failed due to: ' + status);
                    }
                });
            });
        }

        function add_place(address, lat, lng){
            
            var request = $.ajax({
                url: "/create_place/",
                type: "POST",
                data: { address : address, lat : lat, lng : lng }
            });

            request.done(function(result) {
                console.log(result);
                var place_rows_count = $("#places tbody.place_rows tr").length;
                row = " <tr> \
                            <th scope=\"row\">"+(place_rows_count+1)+"</th> \
                            <td>"+result.address+"</td> \
                            <td>"+result.lat+"</td> \
                            <td>"+result.lon+"</td> \
                        </tr>"
                $("#places tbody").append(row);
            });

            request.fail(function(jqXHR, textStatus) {
                alert( "Request failed: " + textStatus );
            });
        }

      
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGqMRd71q6yQlnz02MifWbH5_KtdBV7Y8&callback=initMap"
    async defer></script>
{% endblock %}

templates/includes/header.html
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'gmapdemo:home' %}"> Dashboard |</a>
      <a class="navbar-brand" href="{% url 'gmapdemo:clear_database' %}">Clear Database </a>
    </div>
  </div>
</nav>